// <auto-generated />
using System;
using ComicAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComicAPI.Migrations
{
    [DbContext(typeof(ComicDbContext))]
    [Migration("20260702132208_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ComicAPI.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 7, 2, 13, 22, 7, 171, DateTimeKind.Utc).AddTicks(4215),
                            Name = "Action",
                            Slug = "action",
                            Tag = "Action-packed comics",
                            UpdatedAt = new DateTime(2026, 7, 2, 13, 22, 7, 171, DateTimeKind.Utc).AddTicks(4216)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 7, 2, 13, 22, 7, 171, DateTimeKind.Utc).AddTicks(4222),
                            Name = "Romance",
                            Slug = "romance",
                            Tag = "Romantic stories",
                            UpdatedAt = new DateTime(2026, 7, 2, 13, 22, 7, 171, DateTimeKind.Utc).AddTicks(4222)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 7, 2, 13, 22, 7, 171, DateTimeKind.Utc).AddTicks(4225),
                            Name = "Comedy",
                            Slug = "comedy",
                            Tag = "Funny and hilarious",
                            UpdatedAt = new DateTime(2026, 7, 2, 13, 22, 7, 171, DateTimeKind.Utc).AddTicks(4225)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 7, 2, 13, 22, 7, 171, DateTimeKind.Utc).AddTicks(4227),
                            Name = "Fantasy",
                            Slug = "fantasy",
                            Tag = "Magical worlds",
                            UpdatedAt = new DateTime(2026, 7, 2, 13, 22, 7, 171, DateTimeKind.Utc).AddTicks(4228)
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2026, 7, 2, 13, 22, 7, 171, DateTimeKind.Utc).AddTicks(4230),
                            Name = "Horror",
                            Slug = "horror",
                            Tag = "Scary and thrilling",
                            UpdatedAt = new DateTime(2026, 7, 2, 13, 22, 7, 171, DateTimeKind.Utc).AddTicks(4230)
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            CreatedAt = new DateTime(2026, 7, 2, 13, 22, 7, 171, DateTimeKind.Utc).AddTicks(4232),
                            Name = "Sci-Fi",
                            Slug = "sci-fi",
                            Tag = "Science fiction",
                            UpdatedAt = new DateTime(2026, 7, 2, 13, 22, 7, 171, DateTimeKind.Utc).AddTicks(4233)
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            CreatedAt = new DateTime(2026, 7, 2, 13, 22, 7, 171, DateTimeKind.Utc).AddTicks(4235),
                            Name = "Slice of Life",
                            Slug = "slice-of-life",
                            Tag = "Everyday life",
                            UpdatedAt = new DateTime(2026, 7, 2, 13, 22, 7, 171, DateTimeKind.Utc).AddTicks(4236)
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            CreatedAt = new DateTime(2026, 7, 2, 13, 22, 7, 171, DateTimeKind.Utc).AddTicks(4243),
                            Name = "Drama",
                            Slug = "drama",
                            Tag = "Emotional and dramatic",
                            UpdatedAt = new DateTime(2026, 7, 2, 13, 22, 7, 171, DateTimeKind.Utc).AddTicks(4244)
                        });
                });

            modelBuilder.Entity("ComicAPI.Entities.Comic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SalaryType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Comics");
                });

            modelBuilder.Entity("ComicAPI.Entities.ComicCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ComicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ComicId");

                    b.ToTable("ComicCategories");
                });

            modelBuilder.Entity("ComicAPI.Entities.Outstanding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ComicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ComicId");

                    b.ToTable("Outstandings");
                });

            modelBuilder.Entity("ComicAPI.Entities.ComicCategory", b =>
                {
                    b.HasOne("ComicAPI.Entities.Category", "Category")
                        .WithMany("ComicCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComicAPI.Entities.Comic", "Comic")
                        .WithMany("ComicCategories")
                        .HasForeignKey("ComicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Comic");
                });

            modelBuilder.Entity("ComicAPI.Entities.Outstanding", b =>
                {
                    b.HasOne("ComicAPI.Entities.Comic", "Comic")
                        .WithMany("Outstandings")
                        .HasForeignKey("ComicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comic");
                });

            modelBuilder.Entity("ComicAPI.Entities.Category", b =>
                {
                    b.Navigation("ComicCategories");
                });

            modelBuilder.Entity("ComicAPI.Entities.Comic", b =>
                {
                    b.Navigation("ComicCategories");

                    b.Navigation("Outstandings");
                });
#pragma warning restore 612, 618
        }
    }
}
